// app/layout.tsx
import type { Metadata } from "next";
import { IBM_Plex_Mono, Outfit } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { TransitionProvider } from "@/components/contexts/TransitionContext";
import ClientLayout from "@/components/ui/ClientLayout";
import ContainerProvider from "@/components/ui/ContainerProvider";

const geistSans = IBM_Plex_Mono({
  variable: "--font-ibm-plex-mono",
  weight: "700",
});

const geistMono = Outfit({
  variable: "--font-outfit",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TransitionProvider>
          <ClientLayout>
            <Navbar />
            <ContainerProvider>{children}</ContainerProvider>
            <Footer />
          </ClientLayout>
        </TransitionProvider>
      </body>
    </html>
  );
}
